<a href="https://colab.research.google.com/github/PhongCT1105/Pytorch_Learning/blob/main/Session_0_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
torch.__version__

'2.6.0+cu124'

### I. Creating Tensors

In [ ]:
# Create

x = torch.tensor([[[1,2,3],
                  [4,5,6],
                  [7,8,9],
                  [10,11,12]]])
print(x)

print("Shape: ", x.shape)
print("Dimensions: ", x.ndim)
print("Scalar: ", x[0][1][1])

# ndim: N_dimensions Total dimensions
# shape: Size of each dimensions
# => ndim is just len of shape

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]])
Shape:  torch.Size([1, 4, 3])
Dimensions:  3
Scalar:  tensor(5)


In [ ]:
# Random tensor

rand_tensor = torch.rand(5,2,10)
print(rand_tensor)
print("Shape: ", rand_tensor.shape)
print("Dimensions: ", rand_tensor.ndim)

tensor([[[0.0483, 0.4806, 0.7565, 0.4332, 0.0433, 0.4459, 0.0920, 0.1246,
          0.5641, 0.1031],
         [0.7175, 0.9589, 0.3951, 0.2381, 0.5017, 0.4763, 0.3854, 0.5095,
          0.1963, 0.9986]],

        [[0.6332, 0.6125, 0.1566, 0.8509, 0.9050, 0.8543, 0.8807, 0.4677,
          0.6936, 0.0174],
         [0.9112, 0.2807, 0.4042, 0.9391, 0.0621, 0.9786, 0.3168, 0.3035,
          0.6658, 0.5319]],

        [[0.0069, 0.7200, 0.2728, 0.8494, 0.8245, 0.1852, 0.3520, 0.9473,
          0.2838, 0.8627],
         [0.5487, 0.3885, 0.1947, 0.9287, 0.1095, 0.3478, 0.8371, 0.1861,
          0.2805, 0.8731]],

        [[0.0833, 0.2499, 0.0511, 0.4641, 0.5134, 0.8908, 0.6799, 0.9141,
          0.5365, 0.2868],
         [0.3584, 0.7648, 0.6074, 0.0171, 0.0572, 0.7600, 0.2211, 0.2918,
          0.9252, 0.0383]],

        [[0.7453, 0.2322, 0.0118, 0.6962, 0.2789, 0.7166, 0.7533, 0.4768,
          0.9968, 0.9561],
         [0.3373, 0.7655, 0.9148, 0.0995, 0.4652, 0.7304, 0.0516, 0.5485,
         

In [ ]:
# 0 and 1 tensor for Masking
zeros = torch.zeros(size=(3,4), dtype=torch.float32)
ones = torch.ones(size = (2,3), dtype=torch.int)

print(zeros)
print(ones)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


In [ ]:
# Create a tensor with same shape

tensor_range = torch.arange(start = 1, end = 10, step = 2)
tensor_copy = torch.zeros_like(tensor_range)

print("Original Tensor: ", tensor_range)
print("New Tensor: ", tensor_copy)

Original Tensor:  tensor([1, 3, 5, 7, 9])
New Tensor:  tensor([0, 0, 0, 0, 0])


In [ ]:
# Tensor Atributes

# dtype: Datatype, default float32, can change to float16 if want trade off speed and precision
tensor_type = torch.tensor([3,4,5,6], dtype=torch.float16)

# device: what device tensor is stored on
tensor_type = torch.tensor([3,4,5,6], dtype=torch.float32, device = "cpu", requires_grad=False)

print(tensor_type)

# Print tensor information
print(tensor_type.dtype)
print(tensor_type.device)
print(tensor_type.shape)


tensor([3., 4., 5., 6.])
torch.float32
cpu
torch.Size([4])


### II. Math with Tensors

In [ ]:
# Create Tensor:
x = torch.tensor([[1,2,3],
                  [4,5,6]], dtype=torch.float32)

print(x.shape)

y = torch.tensor([[7,8,9]], dtype=torch.float32)
print(y.shape)

# Tranpose:
y = y.T
print("Tranpose Y for matmul: ", y.shape)

# Add
print("Add: ", x + 10)

# Multiply / Element-wise  multiplication
print("Multiply: ", x * 10)

# Substract
print("Subtract: ", x - 10)

# Divide:
print("Divide: ", x / 10)


# Matrix Multiplication / dot producct
print(torch.matmul(x, y))


torch.Size([2, 3])
torch.Size([1, 3])
Tranpose Y for matmul:  torch.Size([3, 1])
Add:  tensor([[11., 12., 13.],
        [14., 15., 16.]])
Multiply:  tensor([[10., 20., 30.],
        [40., 50., 60.]])
Subtract:  tensor([[-9., -8., -7.],
        [-6., -5., -4.]])
Divide:  tensor([[0.1000, 0.2000, 0.3000],
        [0.4000, 0.5000, 0.6000]])
tensor([[ 50.],
        [122.]])


In [ ]:
# Tensor Aggregation

x = torch.rand(5)
print(x)

tensor([0.4372, 0.7219, 0.1535, 0.2013, 0.4886])


In [ ]:
# Max
print(torch.max(x))

# Min
print(torch.min(x))

# Average
print(torch.mean(x))

# Sum
print(torch.sum(x))

tensor(0.7219)
tensor(0.1535)
tensor(0.4005)
tensor(2.0024)


In [ ]:
# Positional Agg
print(torch.argmax(x))

print(torch.argmin(x))

tensor(1)
tensor(2)


### III. Reshaping, stacking, squeezing

In [ ]:
x = torch.rand(10)

x, x.shape

# => Shape = 10, so can reshape to any shape that multiplication equal to 1o

(tensor([0.7400, 0.2708, 0.8523, 0.1773, 0.3782, 0.6444, 0.7663, 0.7335, 0.6042,
         0.1907]),
 torch.Size([10]))

In [ ]:
# Reshapes an input tensor to a specific shape

x_reshaped = x.reshape(5, 2)
z = x.view(2,5)
x_reshaped,z

(tensor([[0.7400, 0.2708],
         [0.8523, 0.1773],
         [0.3782, 0.6444],
         [0.7663, 0.7335],
         [0.6042, 0.1907]]),
 tensor([[0.7400, 0.2708, 0.8523, 0.1773, 0.3782],
         [0.6444, 0.7663, 0.7335, 0.6042, 0.1907]]))

In [ ]:
# Stacking tensor on top of each other
x = torch.rand(1,2,5)
print(x)


x_stacked = torch.stack([x,x,x,x], dim = 0)
x_stacked

tensor([[[0.6004, 0.4009, 0.8210, 0.1500, 0.4957],
         [0.6034, 0.7103, 0.1370, 0.0749, 0.5188]]])


tensor([[[[0.6004, 0.4009, 0.8210, 0.1500, 0.4957],
          [0.6034, 0.7103, 0.1370, 0.0749, 0.5188]]],


        [[[0.6004, 0.4009, 0.8210, 0.1500, 0.4957],
          [0.6034, 0.7103, 0.1370, 0.0749, 0.5188]]],


        [[[0.6004, 0.4009, 0.8210, 0.1500, 0.4957],
          [0.6034, 0.7103, 0.1370, 0.0749, 0.5188]]],


        [[[0.6004, 0.4009, 0.8210, 0.1500, 0.4957],
          [0.6034, 0.7103, 0.1370, 0.0749, 0.5188]]]])

In [ ]:
# Squeeze is remove all 1 dimension
print(x.shape)
print(x.squeeze().shape)
print(x.unsqueeze(dim = 2).shape)

torch.Size([1, 2, 5])
torch.Size([2, 5])
torch.Size([1, 2, 1, 5])


In [ ]:
# Permutes

x = torch.rand(1,2,5)
print(x.shape)

x_permute = torch.permute(x, (2,1,0))
print(x_permute.shape)

torch.Size([1, 2, 5])
torch.Size([5, 2, 1])


### III. Indexing (Simmilar to Numpy)

In [ ]:
x = torch.arange(1, 10).reshape(1,3,3)

print(x)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [ ]:
# Normal indexing
print(x[0][2][1])
print(x[0,2,1])

# : to all
print(x[:, 0])

print(x[:,:,2])

tensor(8)
tensor(8)
tensor([[1, 2, 3]])
tensor([[3, 6, 9]])


### IV. Reproducibility (Random Seed)

In [ ]:
SEED = 42

# Use seed before any random function
torch.manual_seed(SEED)
x = torch.rand (3,4)
# Seed no more effect after somme random function execute

torch.manual_seed(SEED)
y = torch.rand (3,4)

print(x == y)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### V. Accessing GPU

In [ ]:
!nvidia-smi

Sun May 18 16:40:31 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-SXM4-40GB          Off |   00000000:00:04.0 Off |                    0 |
| N/A   31C    P0             47W /  400W |       0MiB /  40960MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+-----

In [ ]:
# Check GPU access with Pytorch
import torch
torch.cuda.is_available()

True

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Create tensor (default on the cpu)
tensor = torch.tensor([1,2,3])

tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
# Move to GPU
tensor = tensor.to(device)
print(tensor, tensor.device)

# Move to CPU
tensor = tensor.cpu()
print(tensor, tensor.device)


tensor([1, 2, 3], device='cuda:0') cuda:0
tensor([1, 2, 3]) cpu


### VI. Exercise